config/routes.rb
Rails.application.routes.draw do
  resources :task_labors
  resources :task_administratives
  resources :professions
  resources :clients
  resources :labor_processes
  resources :administrative_processes
  devise_for :users
  get 'home/index'
  root 'home#index'

  namespace :user do
    resources :problems
    resources :services
    devise_scope :user do
      post "/sign_in", :to => 'sessions#create'
      post "/sign_up", :to => 'registrations#create'
      delete "/sign_out", :to => 'sessions#destroy'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/administrative_processes_controller.rb
class AdministrativeProcessesController < ApplicationController
  before_action :set_administrative_process, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!
  
  # GET /administrative_processes
  # GET /administrative_processes.json
  def index
    @administrative_processes = AdministrativeProcess.all
  end

  # GET /administrative_processes/1
  # GET /administrative_processes/1.json
  def show
  end

  # GET /administrative_processes/new
  def new
    @administrative_process = AdministrativeProcess.new
  end

  # GET /administrative_processes/1/edit
  def edit
  end

  # POST /administrative_processes
  # POST /administrative_processes.json
  def create
    @administrative_process = AdministrativeProcess.new(administrative_process_params)

    respond_to do |format|
      if @administrative_process.save
        format.html { redirect_to @administrative_process, notice: 'Administrative process was successfully created.' }
        format.json { render :show, status: :created, location: @administrative_process }
      else
        format.html { render :new }
        format.json { render json: @administrative_process.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrative_processes/1
  # PATCH/PUT /administrative_processes/1.json
  def update
    respond_to do |format|
      if @administrative_process.update(administrative_process_params)
        format.html { redirect_to @administrative_process, notice: 'Administrative process was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrative_process }
      else
        format.html { render :edit }
        format.json { render json: @administrative_process.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrative_processes/1
  # DELETE /administrative_processes/1.json
  def destroy
    @administrative_process.destroy
    respond_to do |format|
      format.html { redirect_to administrative_processes_url, notice: 'Administrative process was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrative_process
      @administrative_process = AdministrativeProcess.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrative_process_params
      params.require(:administrative_process).permit(:benefit_type, :der, :age, :contribution_time, :movements, :status)
    end
end

app/helpers/administrative_processes_helper.rb
module AdministrativeProcessesHelper
end

app/views/administrative_processes/_form.html.erb
<%= simple_form_for @administrative_process do |f| %>
  <%= f.input :benefit_type %>
  <%= f.input :der %>
  <%= f.input :age %>
  <%= f.input :contribution_time %>
  <%= f.input :movements %>
  <%= f.input :status %>
  <%= f.button :submit %>
<% end %>

app/views/administrative_processes/edit.html.erb
<h1>Editing Administrative Process</h1>

<%= render 'form', administrative_process: @administrative_process %>

<%= link_to 'Show', @administrative_process %> |
<%= link_to 'Back', administrative_processes_path %>

app/views/administrative_processes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Administrative Processes</h1>

<table>
  <thead>
    <tr>
      <th>Benefit type</th>
      <th>Der</th>
      <th>Age</th>
      <th>Contribution time</th>
      <th>Movements</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @administrative_processes.each do |administrative_process| %>
      <tr>
        <td><%= administrative_process.benefit_type %></td>
        <td><%= administrative_process.der %></td>
        <td><%= administrative_process.age %></td>
        <td><%= administrative_process.contribution_time %></td>
        <td><%= administrative_process.movements %></td>
        <td><%= administrative_process.status %></td>
        <td><%= link_to 'Show', administrative_process %></td>
        <td><%= link_to 'Edit', edit_administrative_process_path(administrative_process) %></td>
        <td><%= link_to 'Destroy', administrative_process, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Administrative Process', new_administrative_process_path %>
  </br></br>
  <%= current_user.email %>
  </br>
  <%= link_to "Home", root_path %>
  </br>
  <%= link_to "Desconectar", destroy_user_session_path, method: :delete %>
<% end %>

app/views/administrative_processes/new.html.erb
<h1>New Administrative Process</h1>

<%= render 'form', administrative_process: @administrative_process %>

<%= link_to 'Back', administrative_processes_path %>

app/views/administrative_processes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Benefit type:</strong>
  <%= @administrative_process.benefit_type %>
</p>

<p>
  <strong>Der:</strong>
  <%= @administrative_process.der %>
</p>

<p>
  <strong>Age:</strong>
  <%= @administrative_process.age %>
</p>

<p>
  <strong>Contribution time:</strong>
  <%= @administrative_process.contribution_time %>
</p>

<p>
  <strong>Movements:</strong>
  <%= @administrative_process.movements %>
</p>

<p>
  <strong>Status:</strong>
  <%= @administrative_process.status %>
</p>

<%= link_to 'Edit', edit_administrative_process_path(@administrative_process) %> |
<%= link_to 'Back', administrative_processes_path %>