config/routes.rb
Rails.application.routes.draw do
  resources :task_labors
  resources :task_administratives
  resources :professions
  resources :clients
  resources :labor_processes
  resources :administrative_processes
  devise_for :users
  get 'home/index'
  root 'home#index'

  namespace :user do
    resources :problems
    resources :services
    devise_scope :user do
      post "/sign_in", :to => 'sessions#create'
      post "/sign_up", :to => 'registrations#create'
      delete "/sign_out", :to => 'sessions#destroy'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task_administrative.rb
class TaskAdministrative < ApplicationRecord
  belongs_to :administrative_process
end

app/controllers/task_administratives_controller.rb
class TaskAdministrativesController < ApplicationController
  before_action :set_task_administrative, only: [:show, :edit, :update, :destroy]

  # GET /task_administratives
  # GET /task_administratives.json
  def index
    @task_administratives = TaskAdministrative.all
  end

  # GET /task_administratives/1
  # GET /task_administratives/1.json
  def show
  end

  # GET /task_administratives/new
  def new
    @task_administrative = TaskAdministrative.new
  end

  # GET /task_administratives/1/edit
  def edit
  end

  # POST /task_administratives
  # POST /task_administratives.json
  def create
    @task_administrative = TaskAdministrative.new(task_administrative_params)

    respond_to do |format|
      if @task_administrative.save
        format.html { redirect_to @task_administrative, notice: 'Task administrative was successfully created.' }
        format.json { render :show, status: :created, location: @task_administrative }
      else
        format.html { render :new }
        format.json { render json: @task_administrative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_administratives/1
  # PATCH/PUT /task_administratives/1.json
  def update
    respond_to do |format|
      if @task_administrative.update(task_administrative_params)
        format.html { redirect_to @task_administrative, notice: 'Task administrative was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_administrative }
      else
        format.html { render :edit }
        format.json { render json: @task_administrative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_administratives/1
  # DELETE /task_administratives/1.json
  def destroy
    @task_administrative.destroy
    respond_to do |format|
      format.html { redirect_to task_administratives_url, notice: 'Task administrative was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_administrative
      @task_administrative = TaskAdministrative.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_administrative_params
      params.require(:task_administrative).permit(:delivery_date, :task_description, :administrative_process_id)
    end
end

app/helpers/task_administratives_helper.rb
module TaskAdministrativesHelper
end

app/views/task_administratives/_form.html.erb
<%= simple_form_for(@task_administrative) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :delivery_date %>
    <%= f.input :task_description %>


    <div>
      <%= f.label :der %>
      <%= f.collection_select(:administrative_process_id, AdministrativeProcess.all, :id, :der, prompt: true) %>
    </div>


  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/task_administratives/edit.html.erb
<h1>Editing Task Administrative</h1>

<%= render 'form', task_administrative: @task_administrative %>

<%= link_to 'Show', @task_administrative %> |
<%= link_to 'Back', task_administratives_path %>

app/views/task_administratives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Administratives</h1>

<table>
  <thead>
    <tr>
      <th>Delivery date</th>
      <th>Task description</th>
      <th>Administrative process</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_administratives.each do |task_administrative| %>
      <tr>
        <td><%= task_administrative.delivery_date %></td>
        <td><%= task_administrative.task_description %></td>
        <td><%= task_administrative.administrative_process.der %></td>
        <td><%= link_to 'Show', task_administrative %></td>
        <td><%= link_to 'Edit', edit_task_administrative_path(task_administrative) %></td>
        <td><%= link_to 'Destroy', task_administrative, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<% if user_signed_in? %>
  <%= link_to 'New Task', new_task_path %>
  </br></br>
  <%= current_user.email %>
  </br>
  <%= link_to "Home", root_path %>
  </br>
  <%= link_to "Desconectar", destroy_user_session_path, method: :delete %>
<% end %>

app/views/task_administratives/new.html.erb
<h1>New Task Administrative</h1>

<%= render 'form', task_administrative: @task_administrative %>

<%= link_to 'Back', task_administratives_path %>

app/views/task_administratives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Delivery date:</strong>
  <%= @task_administrative.delivery_date %>
</p>

<p>
  <strong>Task description:</strong>
  <%= @task_administrative.task_description %>
</p>

<p>
  <strong>Administrative process:</strong>
  <%= @task_administrative.administrative_process.der %>
</p>

<%= link_to 'Edit', edit_task_administrative_path(@task_administrative) %> |
<%= link_to 'Back', task_administratives_path %>