config/routes.rb
Rails.application.routes.draw do
  resources :task_labors
  resources :task_administratives
  resources :professions
  resources :clients
  resources :labor_processes
  resources :administrative_processes
  devise_for :users
  get 'home/index'
  root 'home#index'

  namespace :user do
    resources :problems
    resources :services
    devise_scope :user do
      post "/sign_in", :to => 'sessions#create'
      post "/sign_up", :to => 'registrations#create'
      delete "/sign_out", :to => 'sessions#destroy'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>LMS Advanced</h1>
<h2>Bem vindo</h2>

<% if user_signed_in? %>
  <ul>
    <li><%= link_to "Profissões", professions_path %></li>
    <li><%= link_to "Clientes", clients_path %></li>
    </br>
    <li><%= link_to "Processo trabalhista", labor_processes_path %></li>
    <li><%= link_to "Tarefas trabalhistas", task_labors_path %></li>
    </br>
    <li><%= link_to "Processo administrativo", administrative_processes_path %></li>
    <li><%= link_to "Tarefas administrativa", task_administratives_path %></li>
  </ul>
  <ul>
    <li><%= current_user.email %></li>
    <li><%= link_to "Desconectar", destroy_user_session_path, method: :delete %></li>
  </ul>
<% else %>
  <ul>
    <li><%= link_to "Logar", new_user_session_path %></li>
    <li><%= link_to "Cadastrar usuário", new_user_registration_path %></li>
  </ul>
<% end %>